apiVersion: v2
name: elasticsearch
description: Chart holder for argo-cd

type: application
version: 7.17.1
appVersion: "7.17.1"

dependencies:
  - name: elasticsearch
    version: 7.17.1
    repository: https://helm.elastic.co
