elasticsearch:
  image: "docker.elastic.co/elasticsearch/elasticsearch"
  imageTag: "8.5.1"
  imagePullPolicy: "IfNotPresent"

  replicas: 1
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
  minimumMasterNodes: 1

  protocol: http
  httpPort: 9200
  #transportPort: 9300

  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: "5Gi"

  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 3
    timeoutSeconds: 5

  extraEnvs:
    - name: discovery.type
      value: single-node
    - name: cluster.name
      value: elasticsearch
    - name: xpack.security.http.ssl.enabled
      value: 'false'
    - name: ELASTIC_USERNAME
      value: elastic
    - name: ELASTIC_PASSWORD
      value: dome_2024!