elasticsearch:
  image: "docker.elastic.co/elasticsearch/elasticsearch"
  imageTag: "7.17.1"
  imagePullPolicy: "IfNotPresent"

  replicas: 1
  minimumMasterNodes: 1
  clusterHealthCheckParams: "wait_for_status=green&timeout=1s"

  protocol: https
  httpPort: 9200
  transportPort: 9300

  esJavaOpts: "-Xms1024m -Xmx1024m"

  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

  networkHost: "0.0.0.0"
  #discovery.seed_hosts: []
  #cluster.initial_master_nodes: []

  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: "5Gi"

  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 3
    timeoutSeconds: 5

#  extraInitContainers:
#    - name: file-permissions
#      image: busybox
#      command: ["chown", "-R", "1000:1000", "/usr/share/elasticsearch/"]
#      volumeMounts:
#        - mountPath: /usr/share/elasticsearch/data
#          name: elasticsearch-master
#      securityContext:
#        privileged: true
#        runAsUser: 0

#  extraEnvs:
#  - name: discovery.type
#    value: single-node
#  - name: cluster.name
#    value: elasticsearch
