apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-argo-application
  namespace: argocd
spec:
  # Every application belongs to a single project
  # If unspecified, an application belongs to the "defalut" project
  project: default

  # Git repository (track and sync)
  source:
    repoURL: https://github.com/pasquy73/dome-search.git
    targetRevision: HEAD
    path: dev

  # k8s cluster
  destination: 
    server: https://kubernetes.default.svc # internal service name of k8s api server
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    # enable automatic sync
    automated:
      selfHeal: true
      prune: true