apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dome-search-ingress
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dome-search-svc
                port:
                  number: 8080