apiVersion: apps/v1
kind: Deployment
metadata:
  name: dome-search-deployment
spec:
  selector:
    matchLabels:
      app: dome-search
  replicas: 1
  template:
    metadata:
      labels:
        app: dome-search
    spec:
      containers:
        - name: search
          image: production.eng.it:8433/dome/search:0.0.6
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          env:
            - name: ELASTICSEARCH_ADDRESS_HOST
              value: dome-elasticsearch-svc
            - name: ELASTICSEARCH_ADDRESS_PORT
              value: "9200"
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 30
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 10
          resources: {}