elasticsearch:
  image: "docker.elastic.co/elasticsearch/elasticsearch"
  imageTag: "7.17.3"
  imagePullPolicy: "IfNotPresent"

  replicas: 1
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
  minimumMasterNodes: 1

  protocol: https
  httpPort: 9200
  transportPort: 9300

  resources:
    requests:
      cpu: "2"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"

  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: "5Gi"

  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 3
    timeoutSeconds: 5

  persistence:
    enabled: false

  sysctlInitContainer:
   enabled: false