apiVersion: v2
name: elasticsearch
description: Chart holder for argo-cd

type: application
version: 8.5.1
appVersion: "8.5.1"

dependencies:
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co
