apiVersion: apps/v1
kind: Deployment
metadata:
  name: dome-elasticsearch-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dome-elasticsearch
      app.kubernetes.io/name: dome-elasticsearch
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: dome-elasticsearch
        app.kubernetes.io/name: dome-elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
          ports:
            - containerPort: 9200
              hostPort: 9200
              protocol: TCP
            - containerPort: 9300
              hostPort: 9300
              protocol: TCP
          env:
            - name: ES_JAVA_OPTS
              value: -Xms1024m -Xmx1024m
            - name: cluster.name
              value: elasticsearch
            - name: discovery.type
              value: single-node
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data
          livenessProbe:
            httpGet:
              port: 9200
              path: /_cluster/health
            initialDelaySeconds: 40
            periodSeconds: 10
          securityContext:
            fsGroup: 1000
          #  privileged: true
          #  runAsUser: 1000
      hostname: elasticsearch
      restartPolicy: Always
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-data
