apiVersion: apps/v1
kind: Deployment
metadata:
  name: dome-elasticsearch-deployment
spec:
  selector:
    matchLabels:
      app: dome-elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: dome-elasticsearch
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms1024m -Xmx1024m
            - name: cluster.name
              value: elasticsearch
            - name: discovery.type
              value: single-node
          image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
          livenessProbe:
            exec:
              command:
                - curl --silent --fail localhost:9200/_cluster/health || exit 1
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 10
          name: elasticsearch
          ports:
            - containerPort: 9200
              hostPort: 9200
              protocol: TCP
            - containerPort: 9300
              hostPort: 9300
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data
      hostname: elasticsearch
      restartPolicy: Always
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-data