apiVersion: v1
kind: Service
metadata:
  name: dome-elasticsearch-svc
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "9300"
      port: 9300
      targetPort: 9300
  selector:
    app: dome-elasticsearch