apiVersion: v1
kind: Service
metadata:
  name: dome-elasticsearch-svc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: dome-elasticsearch
    pp.kubernetes.io/name: dome-elasticsearch
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "9300"
      port: 9300
      targetPort: 9300